#!/bin/bash

set -e

TODAY=$(date +"%Y-%m-%d")

if [ $# -eq 0 ]; then
  read -p "Post title: " TITLE
else
  TITLE=$*
fi

SLUG=$(echo $TITLE | sed 's/ /-/g' | tr "[:upper:]" "[:lower:]")
FILENAME=_posts/$TODAY-$SLUG.md

if [ ! -z $FILENAME ]; then
  echo $FILENAME does not exist
  # The heredoc is indented with actual tabs on purpose
  # <<- removes these in the final file
  cat <<- EOF > $FILENAME
	---
	layout: post
	title: "$TITLE"
	date: $TODAY
	tags: 
	---
	
	EOF
fi

vim +7 $FILENAME
